import NavBarMainPage from "@/components/navbar/NavBarMainPage";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MySessionProvider from "./MySessionProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
          <div className="flex flex-col w-full h-screen min-h-screen">
            <NavBarMainPage />
            <main className="flex-1 flex flex-col items-center w-full p-0 bg-slate-100">
              {children}
            </main>
            <Toaster richColors />
          </div>
        </MySessionProvider>
      </body>
    </html>
  );
}
